import { config } from "dotenv";
config({ path: ".env.local" });
import { isNotNull } from "drizzle-orm";

/**
 * Download every headshot and team mark we reference, resize them, and record
 * which ones we hold in a manifest the app reads at render time.
 *
 *   npm run sync:images -- --dry
 *   npm run sync:images
 *   npm run sync:images -- --force   # re-encode files already cached
 *
 * Safe to re-run: a file already on disk is skipped unless --force, so the
 * usual run only fetches what is new.
 *
 * This deliberately writes NOTHING to the database.
 *
 * It used to repoint players.headshot_url at /headshots/... as it went, and
 * that took the live site's images down. The database is shared with
 * production, so the rewrite reached the deployed site the instant it ran,
 * while the image files it promised existed only on the machine that ran it.
 * Every headshot and logo 404'd until the columns were put back.
 *
 * Hence the manifest. The path is derived from the NBA id at render time and
 * only for ids listed in src/lib/cached-images.ts, which is generated here and
 * committed next to the files it describes. Code, manifest and images ship in
 * one deploy and cannot disagree — there is no ordering to get right and no
 * window where one is ahead of the other.
 */
async function main() {
  const dryRun = process.argv.includes("--dry");
  const force = process.argv.includes("--force");

  const { writeFile, readdir } = await import("node:fs/promises");
  const { join } = await import("node:path");
  const { db } = await import("@/db");
  const { players, teams } = await import("@/db/schema");
  const { cacheHeadshot, cacheTeamLogo } = await import("@/lib/images");

  const teamRows = await db
    .select({ nbaTeamId: teams.nbaTeamId, abbr: teams.abbreviation })
    .from(teams);

  const logoIds: string[] = [];
  const logoMisses: string[] = [];
  for (const t of teamRows) {
    const ok = dryRun ? true : await cacheTeamLogo(t.nbaTeamId, { force });
    if (ok) logoIds.push(t.nbaTeamId);
    else logoMisses.push(t.abbr);
  }
  console.log(
    `  logos: ${logoIds.length}/${teamRows.length}${logoMisses.length ? ` · missing ${logoMisses.join(", ")}` : ""}`,
  );

  /*
   * Every player carrying an NBA id. A player whose id arrived from the daily
   * discovery cron has no cached file yet, and is exactly the row this exists
   * to fill.
   */
  const playerRows = await db
    .select({ nbaPlayerId: players.nbaPlayerId, name: players.fullName })
    .from(players)
    .where(isNotNull(players.nbaPlayerId));

  const headshotIds = new Set<string>();
  const misses: string[] = [];

  for (const p of playerRows) {
    const nbaId = p.nbaPlayerId;
    if (!nbaId || headshotIds.has(nbaId)) continue;

    const path = dryRun ? "dry" : await cacheHeadshot(nbaId, { force });
    // No image on the CDN for this id — the card falls back to initials.
    if (!path) misses.push(p.name);
    else headshotIds.add(nbaId);
  }

  console.log(`  headshots: ${headshotIds.size}/${playerRows.length} cached`);
  if (misses.length) {
    console.log(
      `  no CDN image (${misses.length}): ${misses.slice(0, 8).join(", ")}${misses.length > 8 ? " …" : ""}`,
    );
  }

  if (dryRun) {
    console.log("\n(dry run — nothing downloaded, no manifest written)");
    return;
  }

  /*
   * The manifest is a listing of the directories, not a record of what this
   * run managed to download.
   *
   * That distinction is the safety property. This also runs as a prebuild step
   * on Vercel, where a blocked or flaky cdn.nba.com would fail every fetch —
   * and a manifest built from download successes would then come out empty and
   * blank every image on the site, which is the exact outage this design
   * exists to prevent. Reading the directory instead means the committed files
   * are always listed, a failed fetch simply adds nothing, and the worst case
   * is a new player waiting a deploy for his photo.
   */
  const onDisk = async (dir: string, ext: string) => {
    try {
      const names = await readdir(join(process.cwd(), "public", dir));
      return names.filter((n) => n.endsWith(ext)).map((n) => n.slice(0, -ext.length)).sort();
    } catch {
      return [];
    }
  };
  const haveHeadshots = await onDisk("headshots", ".webp");
  const haveLogos = await onDisk("logos", ".svg");

  const manifest = [
    "/*",
    " * GENERATED by `npm run sync:images` — do not edit by hand.",
    " *",
    " * The ids we hold a resized image for, under public/headshots and",
    " * public/logos. lib/images turns an id into a path only if it is listed",
    " * here, so a page can never request a file this deploy does not carry.",
    " */",
    "",
    `export const CACHED_HEADSHOTS: ReadonlySet<string> = new Set(${JSON.stringify(
      haveHeadshots,
    )});`,
    "",
    `export const CACHED_LOGOS: ReadonlySet<string> = new Set(${JSON.stringify(
      haveLogos,
    )});`,
    "",
  ].join("\n");

  await writeFile(join(process.cwd(), "src", "lib", "cached-images.ts"), manifest);
  console.log(
    `\n  wrote src/lib/cached-images.ts — ${haveHeadshots.length} headshots, ` +
      `${haveLogos.length} logos on disk. Commit it with public/.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
